; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:megaatmega2560]
; Build options: build flags, source filter
platform = atmelavr
; Board options: custom upload port, speed and extra flags
board = megaatmega2560
; Library options: dependencies, extra library storages
framework = arduino
; Advanced options: extra scripting
monitor_speed = 115200
